services:
  api:
    build:
      context: ./vespa-ecommerce-api
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - ./vespa-ecommerce-api:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./vespa-ecommerce-api/.env

  web:
    build:
      context: ./vespa-ecommerce-web
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./vespa-ecommerce-web:/app
    env_file:
      - ./vespa-ecommerce-web/.env.local

  admin:
    build:
      context: ./vespa-ecommerce-admin
      dockerfile: Dockerfile
    ports:
      - "3003:3003" 
    volumes:
      - ./vespa-ecommerce-admin:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./vespa-ecommerce-admin/.env.local 

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine 
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: